# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TakePhotoManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Whisper'
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '1.0.0'
  pod 'Kingfisher'
  pod 'ReachabilitySwift'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FSPagerView'
  pod 'IQKeyboardManager'
  pod 'BSImagePicker', '~> 2.8'

end
